### ISSUE TITLE
Embed code

### ISSUE THREAD

**Issue by KSXGitHub** [linux-man/unreel#1]
I want to display some code in slide without having to edit its source code

**Comment by linux-man** [comment]
Near the end of the demo you have a slide with code syntax highlight. Is that what you need?
On edit mode:
Formats > Blocks > Pre followed by Formats > Inline > Code

**Comment by KSXGitHub** [comment]
Yeah, but I don't see any option to change language (for highlighting)

![image](https://cloud.githubusercontent.com/assets/11488886/25963495/ab72c43e-36ab-11e7-8622-0c23d515871c.png)

**Comment by linux-man** [comment]
That should be automatic. It uses [highlight.js](https://highlightjs.org/), where you can read:
> 174 languages and 77 styles
> automatic language detection
> multi-language code highlighting

and a lot of other good stuff.
You really have to finish editing to see how it looks.

**Comment by KSXGitHub** [comment]
I don't know how many lines I have to write to get highlighting works but sometime I just want to write a short code. Furthermore, I don't think auto language detection is good enough, user should be able to choose language.

![image](https://cloud.githubusercontent.com/assets/11488886/25979577/8c81fb7e-36f3-11e7-9881-4c6aa868324c.png)

**Comment by linux-man** [comment]
![imagem](https://cloud.githubusercontent.com/assets/1733538/25996945/c0494c1e-3711-11e7-9571-510d788f016e.png)
You aren't doing it right!
Code must be inside \<pre>\<code> tags. With
![imagem](https://cloud.githubusercontent.com/assets/1733538/25997029/18e33a92-3712-11e7-8b45-7da5f7cd7470.png)
you get
![imagem](https://cloud.githubusercontent.com/assets/1733538/25997039/2a24e7c4-3712-11e7-9ea4-84aa1dcc4994.png)
Automatic detection may fail. You can choose a language by adding a class to code tag, like this
```
<pre><code class="javascript">
var car = {type:"Fiat", model:"500", color:"white"};
document.getElementById("demo").innerHTML = car.type;
</code></pre>
```
The language list is [here](http://highlightjs.readthedocs.io/en/latest/css-classes-reference.html#language-names-and-aliases).
Before you ask, there's no way to change highlight style.

**Comment by KSXGitHub** [comment]
Is there any way to insert code without opening 'Source Code' dialog? Unreel is not a text editor (like Vim, Sublime, Atom, etc.), it should not ask user to do so.

**Comment by linux-man** [comment]
Yes. Do
![imagem](https://cloud.githubusercontent.com/assets/1733538/25998218/d9b6dfa8-3717-11e7-9a6d-2899622b9d68.png)
![imagem](https://cloud.githubusercontent.com/assets/1733538/25998229/edb22652-3717-11e7-94e3-edec2566675f.png)
and write or paste the code.
You can go to Source Code to choose the language.
Source Code should be used for special formating, and sometimes to clean the HTML mess you can do without knowing (HTML can be really messy :smiley:).

**Comment by KSXGitHub** [comment]
Thanks.
Still, this is tricky. I guess very few people know this.
Can you just add one menu option (Formats > Blocks > Code)?

**Comment by linux-man** [comment]
I could, but I'm a purist: 1 option -> 1 format.
\<pre> and \<code> can stand on their own and be useful to someone...
![imagem](https://cloud.githubusercontent.com/assets/1733538/26000445/e85ab076-3720-11e7-841c-c7daf92ee159.png)

**Comment by KSXGitHub** [comment]
If "pure" means 1 option for 1 html tag, this makes sense
But if 1 option was meant to be 1 visual element, Format > Inline/Block > Code is make symetry

**Comment by linux-man** [comment]
- We don't have to agree, just to understand each other.
- I get your idea, but for now I'm not gonna change formats menu. The one place I wouldn't mind to add a "Syntax Highlight Code Block" would be at "Templates", where you can find other "complex" structures.
- Those 1% that will use syntax highlight like you and me can understand these concepts better than the other 99% that don't need to show their code. After all, syntax highlight is a great "bonus", but seldom used.
- Most important: YOU know how to do it.
- Thank you for using Unreel.

**Comment by linux-man** [comment]
https://github.com/linux-man/unreel/commit/b6262ae88db669c31239e723d78bfa5537f36e89
I'm closing this issue. Fell free to reopen it.
