### ISSUE TITLE
problem with appimage on linux

### ISSUE THREAD

**Issue by freddii** [linux-man/unreel#5]
Error on file "/tmp/.mount_4y6tvr/unreel.desktop": Key file contains line “With Unreel you can create amazing REVEAL.JS presentations” which is not a key-value pair, group, or comment

**Comment by linux-man** [comment]
I got it. The problem affects Desktop integration. I suppose you can run the application, right?
It's easy to fix, and since Reveal.js got an upgrade I'll include the fix on the next release.

**Comment by freddii** [comment]
Yes i can run the application.
