### ISSUE TITLE
Run in backgroung

### ISSUE THREAD

**Issue by dimkiri** [linux-man/unreel#9]
Hi.
I installed the new version and although the installation is going smoothly when I open the program i can not see the working window.
It seems that it is running in the background but there is no application window to interact with the application.

**Comment by dimkiri** [comment]
This is happening in Windows version for a 64bit Windows 11 computer

**Comment by linux-man** [comment]
I presume you see the splash window...
Have you tried the zip version?

**Comment by dimkiri** [comment]
Hi. Apologies it took me so long to respond. 
No I have not tried it. 
I Indeed, can see the splash window but I can not see the main window.
I will try  the zip version And I will let you know.

**Comment by dimkiri** [comment]
Hi I Have unzipped the folder. 
Do I Have to place it in a specific folder to make it work?
The unzip folder does not  seem to run any installation. Is that right?

**Comment by linux-man** [comment]
Yes. Just run unreel.exe.
I'm in the process of upgrading to the latest electron version, but a lot happened in 4 years. It will take some time...

**Comment by dimkiri** [comment]
Hi thank you for replying. This solution does not work for me. I mean that even if I run the .exe file in the zipped file, I get only the splash screen and not the main window. I do not know if there is something I can do to make it run. The issue appeared when I updated to the latest version. 
Anyway I wish you that every thing will run smooth from now on and be well and healthy. 
My best regards and thank you again.
